### ISSUE TITLE
Github Branches and Pull Requests

### ISSUE THREAD

**Issue by Pike1868** [Pike1868/Falcons-Trading-Cards#1]
Alright so I think that since I made this repository I can push and commit changes to the master branch (original file). So to make changes you have to create a new branch that is based off the master file and then push changes to that branch(file). After that you create a "pull" request where we can review and compare the changes to the master file and then we can merge the changes to the master copy.  And this is an issue where we can give each other tasks @bdpurvis25

**Comment by bdpurvis25** [comment]
Oh okay I gotcha
